### ISSUE TITLE
Update README with projects using go-fed

### ISSUE THREAD

**Issue by cjslep** [go-fed/activity#73]
The README currently says:

> Who is using this library currently?
> No one. Please let me know if you are using it!

Well, it's out of date. I've been told via Mastodon, I just need to collect links to homepages/repositories/points-of-contact and put them in the README.

**Comment by cjslep** [comment]
If applications could leave the following 3-5 pieces of information, I'll toss it in the README:

- Application Name:
- One-line description:
- Repository web URL:
- Point of contact (optional):
- Home web page (optional):

**Comment by tuxether** [comment]
* Application Name: Anancus
* One-line description: Self-hosted and federated social link aggregation
* Repository web URL: https://gitlab.com/tuxether/anancus
* Point of contact: [tuxether@floss.social](https://floss.social/@tuxether) (Mastodon) or tuxether@protonmail.ch (Email)

**Comment by thebaer** [comment]
* Application Name: Write.as
* One-line description: Simple, privacy-focused blogging platform
* Repository web URL: (not sure if you want to include it since we're not open source yet, but) https://github.com/writeas/Write.as
* Point of contact (optional, github username / mastodon handle / email / etc): @write_as@writing.exchange or hello@write.as
* Home web page (optional): https://write.as

**Comment by thebaer** [comment]
And a new one (open source this time):

Application Name: Read.as
One-line description: Long-form reader built on open protocols
Repository web URL: https://github.com/writeas/Read.as
Point of contact (optional, github username / mastodon handle / email / etc): _same as Write.as_
Home web page (optional): https://read.as

**Comment by cjslep** [comment]
Done in:
3b0d31022cffc9f8ad45f9e12c5702091f057638
and
3b3c8efdd1da14a3b1b401666493fa860f76a2a3
